export const TOGGLE_POPOVER = 'TOGGLE_POPOVER';
export const CLOSE_POPOVER = 'CLOSE_POPOVER';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SELECT_AVATAR = 'SELECT_AVATAR';
export const LOAD_AVATAR = 'LOAD_AVATAR';
export const CANDIDATE_AVATAR = 'CANDIDATE_AVATAR';
export const CLEAN_CANDIDATE_AVATAR = 'CLEAN_CANDIDATE_AVATAR';

export const PRESS_ARROW_UP = 'PRESS_ARROW_UP';
export const PRESS_ARROW_DOWN = 'PRESS_ARROW_DOWN';
export const PRESS_ARROW_LEFT = 'PRESS_ARROW_LEFT';
export const PRESS_ARROW_RIGHT = 'PRESS_ARROW_RIGHT';
